2021-10-25 23:22:40,018:INFO:PyCaret Supervised Module
2021-10-25 23:22:40,127:INFO:ML Usecase: classification
2021-10-25 23:22:40,127:INFO:version 2.3.4
2021-10-25 23:22:40,127:INFO:Initializing setup()
2021-10-25 23:22:40,142:INFO:setup(target=turnover, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree', 'ks': 'KS Statistic Plot'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=['yearsAtCompany'], numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=True, normalize_method=minmax, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=True, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=True, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2021-10-25 23:22:40,142:INFO:Checking environment
2021-10-25 23:22:40,142:INFO:python_version: 3.8.8
2021-10-25 23:22:40,142:INFO:python_build: ('default', 'Apr 13 2021 15:08:03')
2021-10-25 23:22:40,142:INFO:machine: AMD64
2021-10-25 23:22:40,236:INFO:platform: Windows-10-10.0.19041-SP0
2021-10-25 23:22:40,267:INFO:Memory: svmem(total=4110647296, available=786194432, percent=80.9, used=3324452864, free=786194432)
2021-10-25 23:22:40,267:INFO:Physical Core: 4
2021-10-25 23:22:40,267:INFO:Logical Core: 4
2021-10-25 23:22:40,267:INFO:Checking libraries
2021-10-25 23:22:40,267:INFO:pd==1.2.4
2021-10-25 23:22:40,267:INFO:numpy==1.20.1
2021-10-25 23:22:40,267:INFO:sklearn==0.24.1
2021-10-25 23:22:40,267:INFO:lightgbm==3.3.0
2021-10-25 23:22:40,267:WARNING:catboost not found
2021-10-25 23:22:40,267:WARNING:xgboost not found
2021-10-25 23:22:47,084:INFO:mlflow==1.21.0
2021-10-25 23:22:47,084:INFO:Checking Exceptions
2021-10-25 23:22:47,240:INFO:Declaring global variables
2021-10-25 23:22:47,256:INFO:USI: 03f4
2021-10-25 23:22:47,256:INFO:pycaret_globals: {'_internal_pipeline', 'fold_param', 'USI', 'pycaret_globals', 'stratify_param', 'master_model_container', 'log_plots_param', 'y', 'experiment__', 'create_model_container', 'imputation_regressor', '_all_models', 'fold_shuffle_param', 'fix_imbalance_method_param', 'fold_generator', 'fold_groups_param_full', 'html_param', 'y_train', 'y_test', 'target_param', 'n_jobs_param', 'logging_param', 'X_test', 'imputation_classifier', 'fix_imbalance_param', 'X', '_gpu_n_jobs_param', 'iterative_imputation_iters_param', 'exp_name_log', 'data_before_preprocess', 'gpu_param', '_all_models_internal', 'X_train', 'display_container', '_ml_usecase', 'prep_pipe', 'transform_target_param', '_available_plots', 'transform_target_method_param', 'seed', '_all_metrics', 'fold_groups_param'}
2021-10-25 23:22:47,256:INFO:Preparing display monitor
2021-10-25 23:22:47,256:INFO:Preparing display monitor
2021-10-25 23:22:50,840:INFO:Importing libraries
2021-10-25 23:22:50,876:INFO:Copying data for preprocessing
2021-10-25 23:22:51,241:INFO:Declaring preprocessing parameters
2021-10-25 23:22:51,297:INFO:Creating preprocessing pipeline
2021-10-25 23:22:53,016:INFO:Preprocessing pipeline created successfully
2021-10-25 23:22:53,016:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2021-10-25 23:22:53,047:INFO:Creating global containers
2021-10-25 23:22:53,248:INFO:Internal pipeline: Pipeline(memory=None,
         steps=[('fix_imbalance',
                 SMOTE(k_neighbors=5, n_jobs=None, random_state=5654,
                       sampling_strategy='auto'))],
         verbose=False)
2021-10-26 00:25:15,054:WARNING:Couldn't import xgboost.XGBClassifier
2021-10-26 00:25:15,054:WARNING:Couldn't import catboost.CatBoostClassifier
2021-10-26 00:25:15,695:WARNING:Couldn't import xgboost.XGBClassifier
2021-10-26 00:25:15,695:WARNING:Couldn't import catboost.CatBoostClassifier
2021-10-26 00:25:15,727:INFO:Creating grid variables
2021-10-26 00:25:15,962:INFO:create_model_container: 0
2021-10-26 00:25:15,962:INFO:master_model_container: 0
2021-10-26 00:25:15,962:INFO:display_container: 1
2021-10-26 00:25:36,081:INFO:Initializing compare_models()
2021-10-26 00:25:36,082:INFO:compare_models(include=None, fold=5, round=4, cross_validation=True, sort=AUC, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, verbose=True, display=None, exclude=None)
2021-10-26 00:25:36,082:INFO:Checking exceptions
2021-10-26 00:25:36,163:INFO:Preparing display monitor
2021-10-26 00:25:36,163:INFO:Preparing display monitor
2021-10-26 00:25:36,456:INFO:Initializing Logistic Regression
2021-10-26 00:25:36,456:INFO:Total runtime is 1.6673405965169272e-05 minutes
2021-10-26 00:25:36,520:INFO:SubProcess create_model() called ==================================
2021-10-26 00:25:36,559:INFO:Initializing create_model()
2021-10-26 00:25:36,560:INFO:create_model(estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:25:36,561:INFO:Checking exceptions
2021-10-26 00:25:36,561:INFO:Importing libraries
2021-10-26 00:25:36,562:INFO:Copying training dataset
2021-10-26 00:25:36,564:INFO:Defining folds
2021-10-26 00:25:36,565:INFO:Declaring metric variables
2021-10-26 00:25:36,607:INFO:Importing untrained model
2021-10-26 00:25:36,660:INFO:Logistic Regression Imported succesfully
2021-10-26 00:25:36,751:INFO:Starting cross validation
2021-10-26 00:25:36,791:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:25:58,542:WARNING:create_model() for lr raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:25:58,667:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:25:58,683:INFO:Initializing create_model()
2021-10-26 00:25:58,683:INFO:create_model(estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:25:58,683:INFO:Checking exceptions
2021-10-26 00:25:58,683:INFO:Importing libraries
2021-10-26 00:25:58,683:INFO:Copying training dataset
2021-10-26 00:25:58,683:INFO:Defining folds
2021-10-26 00:25:58,683:INFO:Declaring metric variables
2021-10-26 00:25:58,796:INFO:Importing untrained model
2021-10-26 00:25:58,837:INFO:Logistic Regression Imported succesfully
2021-10-26 00:25:58,918:INFO:Starting cross validation
2021-10-26 00:25:58,920:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:26:05,838:ERROR:create_model() for lr raised an exception or returned all 0.0:
2021-10-26 00:26:05,838:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:26:05,838:INFO:Initializing K Neighbors Classifier
2021-10-26 00:26:05,838:INFO:Total runtime is 0.4897082249323527 minutes
2021-10-26 00:26:05,929:INFO:SubProcess create_model() called ==================================
2021-10-26 00:26:05,930:INFO:Initializing create_model()
2021-10-26 00:26:05,931:INFO:create_model(estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:26:05,931:INFO:Checking exceptions
2021-10-26 00:26:05,932:INFO:Importing libraries
2021-10-26 00:26:05,934:INFO:Copying training dataset
2021-10-26 00:26:05,938:INFO:Defining folds
2021-10-26 00:26:05,939:INFO:Declaring metric variables
2021-10-26 00:26:05,976:INFO:Importing untrained model
2021-10-26 00:26:06,025:INFO:K Neighbors Classifier Imported succesfully
2021-10-26 00:26:06,106:INFO:Starting cross validation
2021-10-26 00:26:06,140:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:26:13,198:WARNING:create_model() for knn raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:26:13,198:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:26:13,198:INFO:Initializing create_model()
2021-10-26 00:26:13,198:INFO:create_model(estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:26:13,198:INFO:Checking exceptions
2021-10-26 00:26:13,198:INFO:Importing libraries
2021-10-26 00:26:13,198:INFO:Copying training dataset
2021-10-26 00:26:13,198:INFO:Defining folds
2021-10-26 00:26:13,198:INFO:Declaring metric variables
2021-10-26 00:26:13,257:INFO:Importing untrained model
2021-10-26 00:26:13,296:INFO:K Neighbors Classifier Imported succesfully
2021-10-26 00:26:13,393:INFO:Starting cross validation
2021-10-26 00:26:13,398:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:26:20,172:ERROR:create_model() for knn raised an exception or returned all 0.0:
2021-10-26 00:26:20,172:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:26:20,172:INFO:Initializing Naive Bayes
2021-10-26 00:26:20,172:INFO:Total runtime is 0.7286043246587117 minutes
2021-10-26 00:26:20,219:INFO:SubProcess create_model() called ==================================
2021-10-26 00:26:20,220:INFO:Initializing create_model()
2021-10-26 00:26:20,221:INFO:create_model(estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:26:20,221:INFO:Checking exceptions
2021-10-26 00:26:20,222:INFO:Importing libraries
2021-10-26 00:26:20,222:INFO:Copying training dataset
2021-10-26 00:26:20,226:INFO:Defining folds
2021-10-26 00:26:20,227:INFO:Declaring metric variables
2021-10-26 00:26:20,264:INFO:Importing untrained model
2021-10-26 00:26:20,298:INFO:Naive Bayes Imported succesfully
2021-10-26 00:26:20,405:INFO:Starting cross validation
2021-10-26 00:26:20,408:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:26:27,162:WARNING:create_model() for nb raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:26:27,162:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:26:27,162:INFO:Initializing create_model()
2021-10-26 00:26:27,162:INFO:create_model(estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:26:27,162:INFO:Checking exceptions
2021-10-26 00:26:27,162:INFO:Importing libraries
2021-10-26 00:26:27,162:INFO:Copying training dataset
2021-10-26 00:26:27,162:INFO:Defining folds
2021-10-26 00:26:27,162:INFO:Declaring metric variables
2021-10-26 00:26:27,209:INFO:Importing untrained model
2021-10-26 00:26:27,245:INFO:Naive Bayes Imported succesfully
2021-10-26 00:26:27,321:INFO:Starting cross validation
2021-10-26 00:26:27,324:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:26:34,271:ERROR:create_model() for nb raised an exception or returned all 0.0:
2021-10-26 00:26:34,271:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:26:34,271:INFO:Initializing Decision Tree Classifier
2021-10-26 00:26:34,271:INFO:Total runtime is 0.963587220509847 minutes
2021-10-26 00:26:34,320:INFO:SubProcess create_model() called ==================================
2021-10-26 00:26:34,321:INFO:Initializing create_model()
2021-10-26 00:26:34,322:INFO:create_model(estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:26:34,324:INFO:Checking exceptions
2021-10-26 00:26:34,325:INFO:Importing libraries
2021-10-26 00:26:34,325:INFO:Copying training dataset
2021-10-26 00:26:34,328:INFO:Defining folds
2021-10-26 00:26:34,329:INFO:Declaring metric variables
2021-10-26 00:26:34,366:INFO:Importing untrained model
2021-10-26 00:26:34,414:INFO:Decision Tree Classifier Imported succesfully
2021-10-26 00:26:34,503:INFO:Starting cross validation
2021-10-26 00:26:34,557:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:26:41,281:WARNING:create_model() for dt raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:26:41,281:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:26:41,281:INFO:Initializing create_model()
2021-10-26 00:26:41,281:INFO:create_model(estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:26:41,281:INFO:Checking exceptions
2021-10-26 00:26:41,281:INFO:Importing libraries
2021-10-26 00:26:41,281:INFO:Copying training dataset
2021-10-26 00:26:41,297:INFO:Defining folds
2021-10-26 00:26:41,297:INFO:Declaring metric variables
2021-10-26 00:26:41,334:INFO:Importing untrained model
2021-10-26 00:26:41,375:INFO:Decision Tree Classifier Imported succesfully
2021-10-26 00:26:41,461:INFO:Starting cross validation
2021-10-26 00:26:41,464:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:26:48,774:ERROR:create_model() for dt raised an exception or returned all 0.0:
2021-10-26 00:26:48,790:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:26:48,790:INFO:Initializing SVM - Linear Kernel
2021-10-26 00:26:48,790:INFO:Total runtime is 1.2055692275365193 minutes
2021-10-26 00:26:48,825:INFO:SubProcess create_model() called ==================================
2021-10-26 00:26:48,827:INFO:Initializing create_model()
2021-10-26 00:26:48,829:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:26:48,830:INFO:Checking exceptions
2021-10-26 00:26:48,830:INFO:Importing libraries
2021-10-26 00:26:48,830:INFO:Copying training dataset
2021-10-26 00:26:48,833:INFO:Defining folds
2021-10-26 00:26:48,834:INFO:Declaring metric variables
2021-10-26 00:26:48,871:INFO:Importing untrained model
2021-10-26 00:26:48,912:INFO:SVM - Linear Kernel Imported succesfully
2021-10-26 00:26:48,993:INFO:Starting cross validation
2021-10-26 00:26:49,045:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:26:55,825:WARNING:create_model() for svm raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:26:55,825:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:26:55,825:INFO:Initializing create_model()
2021-10-26 00:26:55,825:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:26:55,825:INFO:Checking exceptions
2021-10-26 00:26:55,825:INFO:Importing libraries
2021-10-26 00:26:55,825:INFO:Copying training dataset
2021-10-26 00:26:55,840:INFO:Defining folds
2021-10-26 00:26:55,840:INFO:Declaring metric variables
2021-10-26 00:26:55,876:INFO:Importing untrained model
2021-10-26 00:26:55,915:INFO:SVM - Linear Kernel Imported succesfully
2021-10-26 00:26:55,996:INFO:Starting cross validation
2021-10-26 00:26:55,999:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:27:02,887:ERROR:create_model() for svm raised an exception or returned all 0.0:
2021-10-26 00:27:02,887:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:27:02,887:INFO:Initializing Ridge Classifier
2021-10-26 00:27:02,887:INFO:Total runtime is 1.4405287543932597 minutes
2021-10-26 00:27:02,931:INFO:SubProcess create_model() called ==================================
2021-10-26 00:27:02,933:INFO:Initializing create_model()
2021-10-26 00:27:02,934:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:27:02,934:INFO:Checking exceptions
2021-10-26 00:27:02,935:INFO:Importing libraries
2021-10-26 00:27:02,936:INFO:Copying training dataset
2021-10-26 00:27:02,940:INFO:Defining folds
2021-10-26 00:27:02,941:INFO:Declaring metric variables
2021-10-26 00:27:02,979:INFO:Importing untrained model
2021-10-26 00:27:03,042:INFO:Ridge Classifier Imported succesfully
2021-10-26 00:27:03,129:INFO:Starting cross validation
2021-10-26 00:27:03,166:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:27:12,355:WARNING:create_model() for ridge raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:27:12,358:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:27:12,359:INFO:Initializing create_model()
2021-10-26 00:27:12,360:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:27:12,361:INFO:Checking exceptions
2021-10-26 00:27:12,361:INFO:Importing libraries
2021-10-26 00:27:12,361:INFO:Copying training dataset
2021-10-26 00:27:12,364:INFO:Defining folds
2021-10-26 00:27:12,365:INFO:Declaring metric variables
2021-10-26 00:27:12,412:INFO:Importing untrained model
2021-10-26 00:27:12,453:INFO:Ridge Classifier Imported succesfully
2021-10-26 00:27:12,567:INFO:Starting cross validation
2021-10-26 00:27:12,570:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:27:21,964:ERROR:create_model() for ridge raised an exception or returned all 0.0:
2021-10-26 00:27:21,969:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:27:21,970:INFO:Initializing Random Forest Classifier
2021-10-26 00:27:21,971:INFO:Total runtime is 1.758593757947286 minutes
2021-10-26 00:27:22,017:INFO:SubProcess create_model() called ==================================
2021-10-26 00:27:22,022:INFO:Initializing create_model()
2021-10-26 00:27:22,023:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:27:22,024:INFO:Checking exceptions
2021-10-26 00:27:22,024:INFO:Importing libraries
2021-10-26 00:27:22,025:INFO:Copying training dataset
2021-10-26 00:27:22,028:INFO:Defining folds
2021-10-26 00:27:22,029:INFO:Declaring metric variables
2021-10-26 00:27:22,069:INFO:Importing untrained model
2021-10-26 00:27:22,107:INFO:Random Forest Classifier Imported succesfully
2021-10-26 00:27:22,195:INFO:Starting cross validation
2021-10-26 00:27:22,214:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:27:30,319:WARNING:create_model() for rf raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:27:30,319:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:27:30,319:INFO:Initializing create_model()
2021-10-26 00:27:30,319:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:27:30,319:INFO:Checking exceptions
2021-10-26 00:27:30,319:INFO:Importing libraries
2021-10-26 00:27:30,319:INFO:Copying training dataset
2021-10-26 00:27:30,319:INFO:Defining folds
2021-10-26 00:27:30,319:INFO:Declaring metric variables
2021-10-26 00:27:30,369:INFO:Importing untrained model
2021-10-26 00:27:30,411:INFO:Random Forest Classifier Imported succesfully
2021-10-26 00:27:30,495:INFO:Starting cross validation
2021-10-26 00:27:30,501:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:27:38,434:ERROR:create_model() for rf raised an exception or returned all 0.0:
2021-10-26 00:27:38,434:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:27:38,434:INFO:Initializing Quadratic Discriminant Analysis
2021-10-26 00:27:38,434:INFO:Total runtime is 2.0329747279485066 minutes
2021-10-26 00:27:38,485:INFO:SubProcess create_model() called ==================================
2021-10-26 00:27:38,486:INFO:Initializing create_model()
2021-10-26 00:27:38,488:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:27:38,488:INFO:Checking exceptions
2021-10-26 00:27:38,488:INFO:Importing libraries
2021-10-26 00:27:38,489:INFO:Copying training dataset
2021-10-26 00:27:38,492:INFO:Defining folds
2021-10-26 00:27:38,493:INFO:Declaring metric variables
2021-10-26 00:27:38,531:INFO:Importing untrained model
2021-10-26 00:27:38,574:INFO:Quadratic Discriminant Analysis Imported succesfully
2021-10-26 00:27:38,662:INFO:Starting cross validation
2021-10-26 00:27:38,680:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:27:46,859:WARNING:create_model() for qda raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:27:46,859:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:27:46,859:INFO:Initializing create_model()
2021-10-26 00:27:46,859:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:27:46,859:INFO:Checking exceptions
2021-10-26 00:27:46,859:INFO:Importing libraries
2021-10-26 00:27:46,859:INFO:Copying training dataset
2021-10-26 00:27:46,859:INFO:Defining folds
2021-10-26 00:27:46,859:INFO:Declaring metric variables
2021-10-26 00:27:46,944:INFO:Importing untrained model
2021-10-26 00:27:46,990:INFO:Quadratic Discriminant Analysis Imported succesfully
2021-10-26 00:27:47,102:INFO:Starting cross validation
2021-10-26 00:27:47,105:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:27:57,099:ERROR:create_model() for qda raised an exception or returned all 0.0:
2021-10-26 00:27:57,112:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:27:57,113:INFO:Initializing Ada Boost Classifier
2021-10-26 00:27:57,113:INFO:Total runtime is 2.3442874987920126 minutes
2021-10-26 00:27:57,154:INFO:SubProcess create_model() called ==================================
2021-10-26 00:27:57,157:INFO:Initializing create_model()
2021-10-26 00:27:57,158:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:27:57,158:INFO:Checking exceptions
2021-10-26 00:27:57,159:INFO:Importing libraries
2021-10-26 00:27:57,161:INFO:Copying training dataset
2021-10-26 00:27:57,165:INFO:Defining folds
2021-10-26 00:27:57,166:INFO:Declaring metric variables
2021-10-26 00:27:57,215:INFO:Importing untrained model
2021-10-26 00:27:57,257:INFO:Ada Boost Classifier Imported succesfully
2021-10-26 00:27:57,353:INFO:Starting cross validation
2021-10-26 00:27:57,395:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:28:07,075:WARNING:create_model() for ada raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:28:07,075:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:28:07,075:INFO:Initializing create_model()
2021-10-26 00:28:07,075:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:28:07,075:INFO:Checking exceptions
2021-10-26 00:28:07,075:INFO:Importing libraries
2021-10-26 00:28:07,075:INFO:Copying training dataset
2021-10-26 00:28:07,075:INFO:Defining folds
2021-10-26 00:28:07,075:INFO:Declaring metric variables
2021-10-26 00:28:07,120:INFO:Importing untrained model
2021-10-26 00:28:07,158:INFO:Ada Boost Classifier Imported succesfully
2021-10-26 00:28:07,245:INFO:Starting cross validation
2021-10-26 00:28:07,247:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:28:17,532:ERROR:create_model() for ada raised an exception or returned all 0.0:
2021-10-26 00:28:17,540:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:28:17,540:INFO:Initializing Gradient Boosting Classifier
2021-10-26 00:28:17,541:INFO:Total runtime is 2.6847556432088218 minutes
2021-10-26 00:28:17,607:INFO:SubProcess create_model() called ==================================
2021-10-26 00:28:17,609:INFO:Initializing create_model()
2021-10-26 00:28:17,609:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:28:17,610:INFO:Checking exceptions
2021-10-26 00:28:17,611:INFO:Importing libraries
2021-10-26 00:28:17,611:INFO:Copying training dataset
2021-10-26 00:28:17,616:INFO:Defining folds
2021-10-26 00:28:17,621:INFO:Declaring metric variables
2021-10-26 00:28:17,663:INFO:Importing untrained model
2021-10-26 00:28:17,706:INFO:Gradient Boosting Classifier Imported succesfully
2021-10-26 00:28:17,823:INFO:Starting cross validation
2021-10-26 00:28:17,904:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:28:27,455:WARNING:create_model() for gbc raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:28:27,455:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:28:27,455:INFO:Initializing create_model()
2021-10-26 00:28:27,455:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:28:27,455:INFO:Checking exceptions
2021-10-26 00:28:27,455:INFO:Importing libraries
2021-10-26 00:28:27,455:INFO:Copying training dataset
2021-10-26 00:28:27,471:INFO:Defining folds
2021-10-26 00:28:27,471:INFO:Declaring metric variables
2021-10-26 00:28:27,508:INFO:Importing untrained model
2021-10-26 00:28:27,545:INFO:Gradient Boosting Classifier Imported succesfully
2021-10-26 00:28:27,626:INFO:Starting cross validation
2021-10-26 00:28:27,629:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:28:38,419:ERROR:create_model() for gbc raised an exception or returned all 0.0:
2021-10-26 00:28:38,434:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:28:38,434:INFO:Initializing Linear Discriminant Analysis
2021-10-26 00:28:38,434:INFO:Total runtime is 3.0329819242159526 minutes
2021-10-26 00:28:38,469:INFO:SubProcess create_model() called ==================================
2021-10-26 00:28:38,477:INFO:Initializing create_model()
2021-10-26 00:28:38,477:INFO:create_model(estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:28:38,478:INFO:Checking exceptions
2021-10-26 00:28:38,478:INFO:Importing libraries
2021-10-26 00:28:38,478:INFO:Copying training dataset
2021-10-26 00:28:38,481:INFO:Defining folds
2021-10-26 00:28:38,481:INFO:Declaring metric variables
2021-10-26 00:28:38,513:INFO:Importing untrained model
2021-10-26 00:28:38,552:INFO:Linear Discriminant Analysis Imported succesfully
2021-10-26 00:28:38,629:INFO:Starting cross validation
2021-10-26 00:28:38,632:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:28:47,239:WARNING:create_model() for lda raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:28:47,239:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:28:47,239:INFO:Initializing create_model()
2021-10-26 00:28:47,239:INFO:create_model(estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:28:47,239:INFO:Checking exceptions
2021-10-26 00:28:47,239:INFO:Importing libraries
2021-10-26 00:28:47,239:INFO:Copying training dataset
2021-10-26 00:28:47,239:INFO:Defining folds
2021-10-26 00:28:47,254:INFO:Declaring metric variables
2021-10-26 00:28:47,292:INFO:Importing untrained model
2021-10-26 00:28:47,328:INFO:Linear Discriminant Analysis Imported succesfully
2021-10-26 00:28:47,408:INFO:Starting cross validation
2021-10-26 00:28:47,411:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:28:56,209:ERROR:create_model() for lda raised an exception or returned all 0.0:
2021-10-26 00:28:56,209:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:28:56,209:INFO:Initializing Extra Trees Classifier
2021-10-26 00:28:56,209:INFO:Total runtime is 3.3292312542597453 minutes
2021-10-26 00:28:56,262:INFO:SubProcess create_model() called ==================================
2021-10-26 00:28:56,264:INFO:Initializing create_model()
2021-10-26 00:28:56,265:INFO:create_model(estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:28:56,266:INFO:Checking exceptions
2021-10-26 00:28:56,266:INFO:Importing libraries
2021-10-26 00:28:56,267:INFO:Copying training dataset
2021-10-26 00:28:56,270:INFO:Defining folds
2021-10-26 00:28:56,271:INFO:Declaring metric variables
2021-10-26 00:28:56,308:INFO:Importing untrained model
2021-10-26 00:28:56,351:INFO:Extra Trees Classifier Imported succesfully
2021-10-26 00:28:56,431:INFO:Starting cross validation
2021-10-26 00:28:56,454:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:29:05,643:WARNING:create_model() for et raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:29:05,643:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:29:05,643:INFO:Initializing create_model()
2021-10-26 00:29:05,643:INFO:create_model(estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:29:05,643:INFO:Checking exceptions
2021-10-26 00:29:05,643:INFO:Importing libraries
2021-10-26 00:29:05,643:INFO:Copying training dataset
2021-10-26 00:29:05,643:INFO:Defining folds
2021-10-26 00:29:05,643:INFO:Declaring metric variables
2021-10-26 00:29:05,695:INFO:Importing untrained model
2021-10-26 00:29:05,740:INFO:Extra Trees Classifier Imported succesfully
2021-10-26 00:29:05,837:INFO:Starting cross validation
2021-10-26 00:29:05,840:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:29:15,209:ERROR:create_model() for et raised an exception or returned all 0.0:
2021-10-26 00:29:15,215:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:29:15,215:INFO:Initializing Light Gradient Boosting Machine
2021-10-26 00:29:15,216:INFO:Total runtime is 3.646006385485331 minutes
2021-10-26 00:29:15,259:INFO:SubProcess create_model() called ==================================
2021-10-26 00:29:15,261:INFO:Initializing create_model()
2021-10-26 00:29:15,262:INFO:create_model(estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:29:15,262:INFO:Checking exceptions
2021-10-26 00:29:15,263:INFO:Importing libraries
2021-10-26 00:29:15,263:INFO:Copying training dataset
2021-10-26 00:29:15,267:INFO:Defining folds
2021-10-26 00:29:15,268:INFO:Declaring metric variables
2021-10-26 00:29:15,298:INFO:Importing untrained model
2021-10-26 00:29:15,339:INFO:Light Gradient Boosting Machine Imported succesfully
2021-10-26 00:29:15,430:INFO:Starting cross validation
2021-10-26 00:29:15,433:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:29:23,780:WARNING:create_model() for lightgbm raised an exception or returned all 0.0, trying without fit_kwargs:
2021-10-26 00:29:23,780:WARNING:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2166, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:29:23,780:INFO:Initializing create_model()
2021-10-26 00:29:23,780:INFO:create_model(estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000020A9F9E3E80>, kwargs={})
2021-10-26 00:29:23,780:INFO:Checking exceptions
2021-10-26 00:29:23,780:INFO:Importing libraries
2021-10-26 00:29:23,780:INFO:Copying training dataset
2021-10-26 00:29:23,780:INFO:Defining folds
2021-10-26 00:29:23,780:INFO:Declaring metric variables
2021-10-26 00:29:23,823:INFO:Importing untrained model
2021-10-26 00:29:23,859:INFO:Light Gradient Boosting Machine Imported succesfully
2021-10-26 00:29:23,937:INFO:Starting cross validation
2021-10-26 00:29:23,940:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 00:29:31,361:ERROR:create_model() for lightgbm raised an exception or returned all 0.0:
2021-10-26 00:29:31,361:ERROR:joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 404, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 116, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute '_FuncWrapper' on <module 'sklearn.utils.fixes' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 2186, in compare_models
    model, model_fit_time = create_model_supervised(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pycaret\internal\tabular.py", line 3145, in create_model_supervised
    scores = cross_validate(
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    # ignore first 'self' argument for instance methods
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 246, in cross_validate
    return_times=True, return_estimator=return_estimator,
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

2021-10-26 00:29:31,425:INFO:create_model_container: 0
2021-10-26 00:29:31,426:INFO:master_model_container: 0
2021-10-26 00:29:31,426:INFO:display_container: 2
2021-10-26 00:29:31,427:INFO:[]
2021-10-26 00:29:31,427:INFO:compare_models() succesfully completed......................................
2021-10-26 00:29:31,460:INFO:PyCaret Supervised Module
2021-10-26 00:29:31,460:INFO:ML Usecase: classification
2021-10-26 00:29:31,460:INFO:version 2.3.4
2021-10-26 00:29:31,461:INFO:Initializing setup()
2021-10-26 00:29:31,461:INFO:setup(target=turnover, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree', 'ks': 'KS Statistic Plot'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=['yearsAtCompany'], numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=True, normalize_method=minmax, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=True, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=True, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2021-10-26 00:29:31,462:INFO:Checking environment
2021-10-26 00:29:31,462:INFO:python_version: 3.8.8
2021-10-26 00:29:31,463:INFO:python_build: ('default', 'Apr 13 2021 15:08:03')
2021-10-26 00:29:31,463:INFO:machine: AMD64
2021-10-26 00:29:31,463:INFO:platform: Windows-10-10.0.19041-SP0
2021-10-26 00:29:31,466:INFO:Memory: svmem(total=4110647296, available=721240064, percent=82.5, used=3389407232, free=721240064)
2021-10-26 00:29:31,466:INFO:Physical Core: 4
2021-10-26 00:29:31,467:INFO:Logical Core: 4
2021-10-26 00:29:31,468:INFO:Checking libraries
2021-10-26 00:29:31,468:INFO:pd==1.2.4
2021-10-26 00:29:31,469:INFO:numpy==1.20.1
2021-10-26 00:29:31,469:INFO:sklearn==0.24.1
2021-10-26 00:29:31,469:INFO:lightgbm==3.3.0
2021-10-26 00:29:31,473:WARNING:catboost not found
2021-10-26 00:29:31,478:WARNING:xgboost not found
2021-10-26 00:29:31,478:INFO:mlflow==1.21.0
2021-10-26 00:29:31,479:INFO:Checking Exceptions
2021-10-26 00:29:31,480:INFO:Declaring global variables
2021-10-26 00:29:31,480:INFO:USI: 70c8
2021-10-26 00:29:31,480:INFO:pycaret_globals: {'_internal_pipeline', 'fold_param', 'USI', 'pycaret_globals', 'stratify_param', 'master_model_container', 'log_plots_param', 'y', 'experiment__', 'create_model_container', 'imputation_regressor', '_all_models', 'fold_shuffle_param', 'fix_imbalance_method_param', 'fold_generator', 'fold_groups_param_full', 'html_param', 'y_train', 'y_test', 'target_param', 'n_jobs_param', 'logging_param', 'X_test', 'imputation_classifier', 'fix_imbalance_param', 'X', '_gpu_n_jobs_param', 'iterative_imputation_iters_param', 'exp_name_log', 'data_before_preprocess', 'gpu_param', '_all_models_internal', 'X_train', 'display_container', '_ml_usecase', 'prep_pipe', 'transform_target_param', '_available_plots', 'transform_target_method_param', 'seed', '_all_metrics', 'fold_groups_param'}
2021-10-26 00:29:31,481:INFO:Preparing display monitor
2021-10-26 00:29:31,481:INFO:Preparing display monitor
2021-10-26 00:29:31,531:INFO:Importing libraries
2021-10-26 00:29:31,535:INFO:Copying data for preprocessing
2021-10-26 00:29:31,570:INFO:Declaring preprocessing parameters
2021-10-26 00:29:31,575:INFO:Creating preprocessing pipeline
2021-10-26 00:29:31,606:INFO:Preprocessing pipeline created successfully
2021-10-26 00:29:31,607:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2021-10-26 00:29:31,608:INFO:Creating global containers
2021-10-26 00:29:31,617:INFO:Internal pipeline: Pipeline(memory=None,
         steps=[('fix_imbalance',
                 SMOTE(k_neighbors=5, n_jobs=None, random_state=5563,
                       sampling_strategy='auto'))],
         verbose=False)
2021-10-26 10:20:53,115:INFO:PyCaret Supervised Module
2021-10-26 10:20:53,176:INFO:ML Usecase: classification
2021-10-26 10:20:53,177:INFO:version 2.3.4
2021-10-26 10:20:53,177:INFO:Initializing setup()
2021-10-26 10:20:53,177:INFO:setup(target=turnover, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree', 'ks': 'KS Statistic Plot'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=['yearsAtCompany'], numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=True, normalize_method=minmax, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=True, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=True, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2021-10-26 10:20:53,178:INFO:Checking environment
2021-10-26 10:20:53,178:INFO:python_version: 3.8.8
2021-10-26 10:20:53,178:INFO:python_build: ('default', 'Apr 13 2021 15:08:03')
2021-10-26 10:20:53,178:INFO:machine: AMD64
2021-10-26 10:20:53,180:INFO:platform: Windows-10-10.0.19041-SP0
2021-10-26 10:20:53,181:INFO:Memory: svmem(total=4110647296, available=70914048, percent=98.3, used=4039733248, free=70914048)
2021-10-26 10:20:53,182:INFO:Physical Core: 4
2021-10-26 10:20:53,182:INFO:Logical Core: 4
2021-10-26 10:20:53,183:INFO:Checking libraries
2021-10-26 10:20:53,183:INFO:pd==1.2.4
2021-10-26 10:20:53,183:INFO:numpy==1.19.5
2021-10-26 10:20:53,183:INFO:sklearn==0.23.2
2021-10-26 10:20:53,183:INFO:lightgbm==3.3.0
2021-10-26 10:20:53,189:WARNING:catboost not found
2021-10-26 10:20:53,191:WARNING:xgboost not found
2021-10-26 10:21:44,531:INFO:mlflow==1.21.0
2021-10-26 10:21:44,561:INFO:Checking Exceptions
2021-10-26 10:21:44,561:INFO:Declaring global variables
2021-10-26 10:21:44,561:INFO:USI: a579
2021-10-26 10:21:44,561:INFO:pycaret_globals: {'log_plots_param', 'fix_imbalance_method_param', 'seed', '_available_plots', 'transform_target_method_param', 'transform_target_param', 'fold_groups_param_full', 'exp_name_log', 'imputation_classifier', 'fold_generator', 'create_model_container', 'fold_param', 'stratify_param', 'fix_imbalance_param', 'y', '_ml_usecase', 'master_model_container', 'imputation_regressor', 'gpu_param', '_all_metrics', 'USI', 'y_test', 'data_before_preprocess', 'iterative_imputation_iters_param', 'X_train', 'target_param', 'X', 'logging_param', '_all_models', '_internal_pipeline', 'fold_shuffle_param', '_all_models_internal', 'experiment__', 'fold_groups_param', 'X_test', 'pycaret_globals', '_gpu_n_jobs_param', 'display_container', 'html_param', 'y_train', 'n_jobs_param', 'prep_pipe'}
2021-10-26 10:21:44,561:INFO:Preparing display monitor
2021-10-26 10:21:44,561:INFO:Preparing display monitor
2021-10-26 10:21:44,791:INFO:Importing libraries
2021-10-26 10:21:44,791:INFO:Copying data for preprocessing
2021-10-26 10:21:44,830:INFO:Declaring preprocessing parameters
2021-10-26 10:21:44,837:INFO:Creating preprocessing pipeline
2021-10-26 10:21:45,058:INFO:Preprocessing pipeline created successfully
2021-10-26 10:21:45,059:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2021-10-26 10:21:45,060:INFO:Creating global containers
2021-10-26 10:21:45,107:INFO:Internal pipeline: Pipeline(memory=None,
         steps=[('fix_imbalance',
                 SMOTE(k_neighbors=5, n_jobs=None, random_state=1863,
                       sampling_strategy='auto'))],
         verbose=False)
2021-10-26 10:46:44,557:INFO:PyCaret Supervised Module
2021-10-26 10:46:44,604:INFO:ML Usecase: classification
2021-10-26 10:46:44,605:INFO:version 2.3.4
2021-10-26 10:46:44,605:INFO:Initializing setup()
2021-10-26 10:46:44,606:INFO:setup(target=turnover, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree', 'ks': 'KS Statistic Plot'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=['yearsAtCompany'], numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=True, normalize_method=minmax, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=True, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=True, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2021-10-26 10:46:44,606:INFO:Checking environment
2021-10-26 10:46:44,606:INFO:python_version: 3.8.8
2021-10-26 10:46:44,607:INFO:python_build: ('default', 'Apr 13 2021 15:08:03')
2021-10-26 10:46:44,607:INFO:machine: AMD64
2021-10-26 10:46:44,608:INFO:platform: Windows-10-10.0.19041-SP0
2021-10-26 10:46:44,608:INFO:Memory: svmem(total=4110647296, available=132190208, percent=96.8, used=3978457088, free=132190208)
2021-10-26 10:46:44,609:INFO:Physical Core: 4
2021-10-26 10:46:44,609:INFO:Logical Core: 4
2021-10-26 10:46:44,610:INFO:Checking libraries
2021-10-26 10:46:44,610:INFO:pd==1.2.4
2021-10-26 10:46:44,610:INFO:numpy==1.19.5
2021-10-26 10:46:44,610:INFO:sklearn==0.23.2
2021-10-26 10:46:44,611:INFO:lightgbm==3.3.0
2021-10-26 10:46:44,616:WARNING:catboost not found
2021-10-26 10:46:44,621:WARNING:xgboost not found
2021-10-26 10:46:49,424:INFO:mlflow==1.21.0
2021-10-26 10:46:49,424:INFO:Checking Exceptions
2021-10-26 10:46:49,424:INFO:Declaring global variables
2021-10-26 10:46:49,424:INFO:USI: 5a08
2021-10-26 10:46:49,424:INFO:pycaret_globals: {'fold_generator', 'master_model_container', '_all_models', 'seed', 'X_test', 'stratify_param', '_available_plots', 'logging_param', 'y_train', 'display_container', 'data_before_preprocess', 'iterative_imputation_iters_param', 'fix_imbalance_param', 'imputation_classifier', 'experiment__', '_ml_usecase', 'USI', 'pycaret_globals', 'html_param', '_all_metrics', '_internal_pipeline', 'y', 'y_test', '_all_models_internal', 'fold_groups_param', 'fix_imbalance_method_param', 'target_param', 'exp_name_log', 'X_train', 'transform_target_method_param', 'fold_param', '_gpu_n_jobs_param', 'X', 'fold_shuffle_param', 'transform_target_param', 'log_plots_param', 'prep_pipe', 'n_jobs_param', 'fold_groups_param_full', 'imputation_regressor', 'create_model_container', 'gpu_param'}
2021-10-26 10:46:49,424:INFO:Preparing display monitor
2021-10-26 10:46:49,424:INFO:Preparing display monitor
2021-10-26 10:46:49,513:INFO:Importing libraries
2021-10-26 10:46:49,513:INFO:Copying data for preprocessing
2021-10-26 10:46:49,550:INFO:Declaring preprocessing parameters
2021-10-26 10:46:49,557:INFO:Creating preprocessing pipeline
2021-10-26 10:46:49,623:INFO:Preprocessing pipeline created successfully
2021-10-26 10:46:49,624:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2021-10-26 10:46:49,624:INFO:Creating global containers
2021-10-26 10:46:49,629:INFO:Internal pipeline: Pipeline(memory=None,
         steps=[('fix_imbalance',
                 SMOTE(k_neighbors=5, n_jobs=None, random_state=774,
                       sampling_strategy='auto'))],
         verbose=False)
2021-10-26 10:47:22,065:INFO:PyCaret Supervised Module
2021-10-26 10:47:22,066:INFO:ML Usecase: classification
2021-10-26 10:47:22,067:INFO:version 2.3.4
2021-10-26 10:47:22,068:INFO:Initializing setup()
2021-10-26 10:47:22,069:INFO:setup(target=turnover, ml_usecase=classification, available_plots={'parameter': 'Hyperparameters', 'auc': 'AUC', 'confusion_matrix': 'Confusion Matrix', 'threshold': 'Threshold', 'pr': 'Precision Recall', 'error': 'Prediction Error', 'class_report': 'Class Report', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'calibration': 'Calibration Curve', 'vc': 'Validation Curve', 'dimension': 'Dimensions', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'boundary': 'Decision Boundary', 'lift': 'Lift Chart', 'gain': 'Gain Chart', 'tree': 'Decision Tree', 'ks': 'KS Statistic Plot'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=['yearsAtCompany', 'averageMonthlyHours'], numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=True, normalize_method=minmax, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=True, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=True, fold_strategy=stratifiedkfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2021-10-26 10:47:22,069:INFO:Checking environment
2021-10-26 10:47:22,070:INFO:python_version: 3.8.8
2021-10-26 10:47:22,070:INFO:python_build: ('default', 'Apr 13 2021 15:08:03')
2021-10-26 10:47:22,070:INFO:machine: AMD64
2021-10-26 10:47:22,071:INFO:platform: Windows-10-10.0.19041-SP0
2021-10-26 10:47:22,071:INFO:Memory: svmem(total=4110647296, available=118513664, percent=97.1, used=3992133632, free=118513664)
2021-10-26 10:47:22,072:INFO:Physical Core: 4
2021-10-26 10:47:22,072:INFO:Logical Core: 4
2021-10-26 10:47:22,073:INFO:Checking libraries
2021-10-26 10:47:22,074:INFO:pd==1.2.4
2021-10-26 10:47:22,074:INFO:numpy==1.19.5
2021-10-26 10:47:22,074:INFO:sklearn==0.23.2
2021-10-26 10:47:22,075:INFO:lightgbm==3.3.0
2021-10-26 10:47:22,079:WARNING:catboost not found
2021-10-26 10:47:22,082:WARNING:xgboost not found
2021-10-26 10:47:22,082:INFO:mlflow==1.21.0
2021-10-26 10:47:22,082:INFO:Checking Exceptions
2021-10-26 10:47:22,083:INFO:Declaring global variables
2021-10-26 10:47:22,083:INFO:USI: 5c9d
2021-10-26 10:47:22,083:INFO:pycaret_globals: {'fold_generator', 'master_model_container', '_all_models', 'seed', 'X_test', 'stratify_param', '_available_plots', 'logging_param', 'y_train', 'display_container', 'data_before_preprocess', 'iterative_imputation_iters_param', 'fix_imbalance_param', 'imputation_classifier', 'experiment__', '_ml_usecase', 'USI', 'pycaret_globals', 'html_param', '_all_metrics', '_internal_pipeline', 'y', 'y_test', '_all_models_internal', 'fold_groups_param', 'fix_imbalance_method_param', 'target_param', 'exp_name_log', 'X_train', 'transform_target_method_param', 'fold_param', '_gpu_n_jobs_param', 'X', 'fold_shuffle_param', 'transform_target_param', 'log_plots_param', 'prep_pipe', 'n_jobs_param', 'fold_groups_param_full', 'imputation_regressor', 'create_model_container', 'gpu_param'}
2021-10-26 10:47:22,084:INFO:Preparing display monitor
2021-10-26 10:47:22,084:INFO:Preparing display monitor
2021-10-26 10:47:22,131:INFO:Importing libraries
2021-10-26 10:47:22,132:INFO:Copying data for preprocessing
2021-10-26 10:47:22,169:INFO:Declaring preprocessing parameters
2021-10-26 10:47:22,176:INFO:Creating preprocessing pipeline
2021-10-26 10:47:22,205:INFO:Preprocessing pipeline created successfully
2021-10-26 10:47:22,205:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2021-10-26 10:47:22,207:INFO:Creating global containers
2021-10-26 10:47:22,210:INFO:Internal pipeline: Pipeline(memory=None,
         steps=[('fix_imbalance',
                 SMOTE(k_neighbors=5, n_jobs=None, random_state=8185,
                       sampling_strategy='auto'))],
         verbose=False)
2021-10-26 10:47:36,368:WARNING:Couldn't import xgboost.XGBClassifier
2021-10-26 10:47:36,368:WARNING:Couldn't import catboost.CatBoostClassifier
2021-10-26 10:47:36,885:WARNING:Couldn't import xgboost.XGBClassifier
2021-10-26 10:47:36,885:WARNING:Couldn't import catboost.CatBoostClassifier
2021-10-26 10:47:36,885:INFO:Creating grid variables
2021-10-26 10:47:37,019:INFO:create_model_container: 0
2021-10-26 10:47:37,019:INFO:master_model_container: 0
2021-10-26 10:47:37,020:INFO:display_container: 1
2021-10-26 10:47:37,044:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=['yearsAtCompany',
                                                          'averageMonthlyHours'],
                                      target='turnover', time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None...
                ('P_transform', 'passthrough'), ('binn', 'passthrough'),
                ('rem_outliers', 'passthrough'), ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='turnover')),
                ('fix_perfect', Remove_100(target='turnover')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2021-10-26 10:47:37,045:INFO:setup() succesfully completed......................................
2021-10-26 10:47:44,563:INFO:Initializing compare_models()
2021-10-26 10:47:44,565:INFO:compare_models(include=None, fold=5, round=4, cross_validation=True, sort=AUC, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, verbose=True, display=None, exclude=None)
2021-10-26 10:47:44,566:INFO:Checking exceptions
2021-10-26 10:47:44,570:INFO:Preparing display monitor
2021-10-26 10:47:44,571:INFO:Preparing display monitor
2021-10-26 10:47:44,786:INFO:Initializing Logistic Regression
2021-10-26 10:47:44,787:INFO:Total runtime is 1.668532689412435e-05 minutes
2021-10-26 10:47:44,829:INFO:SubProcess create_model() called ==================================
2021-10-26 10:47:44,832:INFO:Initializing create_model()
2021-10-26 10:47:44,833:INFO:create_model(estimator=lr, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:47:44,834:INFO:Checking exceptions
2021-10-26 10:47:44,834:INFO:Importing libraries
2021-10-26 10:47:44,835:INFO:Copying training dataset
2021-10-26 10:47:44,840:INFO:Defining folds
2021-10-26 10:47:44,841:INFO:Declaring metric variables
2021-10-26 10:47:44,880:INFO:Importing untrained model
2021-10-26 10:47:44,946:INFO:Logistic Regression Imported succesfully
2021-10-26 10:47:45,043:INFO:Starting cross validation
2021-10-26 10:47:45,046:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:11,619:INFO:Calculating mean and std
2021-10-26 10:49:12,218:INFO:Creating metrics dataframe
2021-10-26 10:49:12,542:INFO:Uploading results into container
2021-10-26 10:49:12,542:INFO:Uploading model into container now
2021-10-26 10:49:12,542:INFO:create_model_container: 1
2021-10-26 10:49:12,542:INFO:master_model_container: 1
2021-10-26 10:49:12,542:INFO:display_container: 2
2021-10-26 10:49:12,680:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=8185, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2021-10-26 10:49:12,680:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:18,047:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:18,047:INFO:Creating metrics dataframe
2021-10-26 10:49:18,454:INFO:Initializing K Neighbors Classifier
2021-10-26 10:49:18,454:INFO:Total runtime is 1.5611217896143597 minutes
2021-10-26 10:49:18,496:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:18,498:INFO:Initializing create_model()
2021-10-26 10:49:18,499:INFO:create_model(estimator=knn, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:18,499:INFO:Checking exceptions
2021-10-26 10:49:18,499:INFO:Importing libraries
2021-10-26 10:49:18,499:INFO:Copying training dataset
2021-10-26 10:49:18,502:INFO:Defining folds
2021-10-26 10:49:18,503:INFO:Declaring metric variables
2021-10-26 10:49:18,550:INFO:Importing untrained model
2021-10-26 10:49:18,588:INFO:K Neighbors Classifier Imported succesfully
2021-10-26 10:49:18,676:INFO:Starting cross validation
2021-10-26 10:49:18,699:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:20,469:INFO:Calculating mean and std
2021-10-26 10:49:20,472:INFO:Creating metrics dataframe
2021-10-26 10:49:20,489:INFO:Uploading results into container
2021-10-26 10:49:20,490:INFO:Uploading model into container now
2021-10-26 10:49:20,491:INFO:create_model_container: 2
2021-10-26 10:49:20,492:INFO:master_model_container: 2
2021-10-26 10:49:20,492:INFO:display_container: 2
2021-10-26 10:49:20,493:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2021-10-26 10:49:20,494:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:20,702:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:20,702:INFO:Creating metrics dataframe
2021-10-26 10:49:20,918:INFO:Initializing Naive Bayes
2021-10-26 10:49:20,918:INFO:Total runtime is 1.6021958351135255 minutes
2021-10-26 10:49:20,962:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:20,964:INFO:Initializing create_model()
2021-10-26 10:49:20,964:INFO:create_model(estimator=nb, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:20,965:INFO:Checking exceptions
2021-10-26 10:49:20,966:INFO:Importing libraries
2021-10-26 10:49:20,967:INFO:Copying training dataset
2021-10-26 10:49:20,973:INFO:Defining folds
2021-10-26 10:49:20,973:INFO:Declaring metric variables
2021-10-26 10:49:21,021:INFO:Importing untrained model
2021-10-26 10:49:21,065:INFO:Naive Bayes Imported succesfully
2021-10-26 10:49:21,150:INFO:Starting cross validation
2021-10-26 10:49:21,155:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:22,768:INFO:Calculating mean and std
2021-10-26 10:49:22,771:INFO:Creating metrics dataframe
2021-10-26 10:49:22,787:INFO:Uploading results into container
2021-10-26 10:49:22,788:INFO:Uploading model into container now
2021-10-26 10:49:22,789:INFO:create_model_container: 3
2021-10-26 10:49:22,789:INFO:master_model_container: 3
2021-10-26 10:49:22,790:INFO:display_container: 2
2021-10-26 10:49:22,790:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2021-10-26 10:49:22,791:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:22,988:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:22,989:INFO:Creating metrics dataframe
2021-10-26 10:49:23,063:INFO:Initializing Decision Tree Classifier
2021-10-26 10:49:23,063:INFO:Total runtime is 1.6379501700401307 minutes
2021-10-26 10:49:23,112:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:23,113:INFO:Initializing create_model()
2021-10-26 10:49:23,113:INFO:create_model(estimator=dt, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:23,114:INFO:Checking exceptions
2021-10-26 10:49:23,115:INFO:Importing libraries
2021-10-26 10:49:23,116:INFO:Copying training dataset
2021-10-26 10:49:23,119:INFO:Defining folds
2021-10-26 10:49:23,120:INFO:Declaring metric variables
2021-10-26 10:49:23,163:INFO:Importing untrained model
2021-10-26 10:49:23,212:INFO:Decision Tree Classifier Imported succesfully
2021-10-26 10:49:23,302:INFO:Starting cross validation
2021-10-26 10:49:23,305:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:23,896:INFO:Calculating mean and std
2021-10-26 10:49:23,896:INFO:Creating metrics dataframe
2021-10-26 10:49:23,923:INFO:Uploading results into container
2021-10-26 10:49:23,924:INFO:Uploading model into container now
2021-10-26 10:49:23,924:INFO:create_model_container: 4
2021-10-26 10:49:23,925:INFO:master_model_container: 4
2021-10-26 10:49:23,926:INFO:display_container: 2
2021-10-26 10:49:23,928:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=8185, splitter='best')
2021-10-26 10:49:23,928:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:24,112:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:24,112:INFO:Creating metrics dataframe
2021-10-26 10:49:24,190:INFO:Initializing SVM - Linear Kernel
2021-10-26 10:49:24,190:INFO:Total runtime is 1.6567286054293315 minutes
2021-10-26 10:49:24,236:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:24,237:INFO:Initializing create_model()
2021-10-26 10:49:24,238:INFO:create_model(estimator=svm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:24,238:INFO:Checking exceptions
2021-10-26 10:49:24,238:INFO:Importing libraries
2021-10-26 10:49:24,239:INFO:Copying training dataset
2021-10-26 10:49:24,242:INFO:Defining folds
2021-10-26 10:49:24,242:INFO:Declaring metric variables
2021-10-26 10:49:24,287:INFO:Importing untrained model
2021-10-26 10:49:24,329:INFO:SVM - Linear Kernel Imported succesfully
2021-10-26 10:49:24,421:INFO:Starting cross validation
2021-10-26 10:49:24,424:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:26,728:INFO:Calculating mean and std
2021-10-26 10:49:26,728:INFO:Creating metrics dataframe
2021-10-26 10:49:26,744:INFO:Uploading results into container
2021-10-26 10:49:26,744:INFO:Uploading model into container now
2021-10-26 10:49:26,744:INFO:create_model_container: 5
2021-10-26 10:49:26,744:INFO:master_model_container: 5
2021-10-26 10:49:26,744:INFO:display_container: 2
2021-10-26 10:49:27,018:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=8185, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2021-10-26 10:49:27,018:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:27,190:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:27,190:INFO:Creating metrics dataframe
2021-10-26 10:49:27,284:INFO:Initializing Ridge Classifier
2021-10-26 10:49:27,284:INFO:Total runtime is 1.7082905093828837 minutes
2021-10-26 10:49:27,326:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:27,328:INFO:Initializing create_model()
2021-10-26 10:49:27,329:INFO:create_model(estimator=ridge, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:27,329:INFO:Checking exceptions
2021-10-26 10:49:27,330:INFO:Importing libraries
2021-10-26 10:49:27,330:INFO:Copying training dataset
2021-10-26 10:49:27,333:INFO:Defining folds
2021-10-26 10:49:27,334:INFO:Declaring metric variables
2021-10-26 10:49:27,378:INFO:Importing untrained model
2021-10-26 10:49:27,429:INFO:Ridge Classifier Imported succesfully
2021-10-26 10:49:27,502:INFO:Starting cross validation
2021-10-26 10:49:27,502:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:31,142:INFO:Calculating mean and std
2021-10-26 10:49:31,142:INFO:Creating metrics dataframe
2021-10-26 10:49:31,165:INFO:Uploading results into container
2021-10-26 10:49:31,166:INFO:Uploading model into container now
2021-10-26 10:49:31,167:INFO:create_model_container: 6
2021-10-26 10:49:31,169:INFO:master_model_container: 6
2021-10-26 10:49:31,169:INFO:display_container: 2
2021-10-26 10:49:31,170:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize=False, random_state=8185,
                solver='auto', tol=0.001)
2021-10-26 10:49:31,171:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:31,359:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:31,359:INFO:Creating metrics dataframe
2021-10-26 10:49:31,437:INFO:Initializing Random Forest Classifier
2021-10-26 10:49:31,437:INFO:Total runtime is 1.7775118311246236 minutes
2021-10-26 10:49:31,491:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:31,492:INFO:Initializing create_model()
2021-10-26 10:49:31,493:INFO:create_model(estimator=rf, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:31,494:INFO:Checking exceptions
2021-10-26 10:49:31,494:INFO:Importing libraries
2021-10-26 10:49:31,495:INFO:Copying training dataset
2021-10-26 10:49:31,498:INFO:Defining folds
2021-10-26 10:49:31,499:INFO:Declaring metric variables
2021-10-26 10:49:31,542:INFO:Importing untrained model
2021-10-26 10:49:31,588:INFO:Random Forest Classifier Imported succesfully
2021-10-26 10:49:31,681:INFO:Starting cross validation
2021-10-26 10:49:31,683:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:40,629:INFO:Calculating mean and std
2021-10-26 10:49:40,629:INFO:Creating metrics dataframe
2021-10-26 10:49:40,644:INFO:Uploading results into container
2021-10-26 10:49:40,644:INFO:Uploading model into container now
2021-10-26 10:49:40,659:INFO:create_model_container: 7
2021-10-26 10:49:40,660:INFO:master_model_container: 7
2021-10-26 10:49:40,660:INFO:display_container: 2
2021-10-26 10:49:40,662:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=8185, verbose=0,
                       warm_start=False)
2021-10-26 10:49:40,662:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:40,859:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:40,859:INFO:Creating metrics dataframe
2021-10-26 10:49:40,937:INFO:Initializing Quadratic Discriminant Analysis
2021-10-26 10:49:40,937:INFO:Total runtime is 1.9358481605847677 minutes
2021-10-26 10:49:40,990:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:40,992:INFO:Initializing create_model()
2021-10-26 10:49:40,993:INFO:create_model(estimator=qda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:40,994:INFO:Checking exceptions
2021-10-26 10:49:40,994:INFO:Importing libraries
2021-10-26 10:49:40,995:INFO:Copying training dataset
2021-10-26 10:49:40,998:INFO:Defining folds
2021-10-26 10:49:40,999:INFO:Declaring metric variables
2021-10-26 10:49:41,045:INFO:Importing untrained model
2021-10-26 10:49:41,088:INFO:Quadratic Discriminant Analysis Imported succesfully
2021-10-26 10:49:41,161:INFO:Starting cross validation
2021-10-26 10:49:41,164:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:42,374:INFO:Calculating mean and std
2021-10-26 10:49:42,374:INFO:Creating metrics dataframe
2021-10-26 10:49:42,400:INFO:Uploading results into container
2021-10-26 10:49:42,401:INFO:Uploading model into container now
2021-10-26 10:49:42,401:INFO:create_model_container: 8
2021-10-26 10:49:42,402:INFO:master_model_container: 8
2021-10-26 10:49:42,402:INFO:display_container: 2
2021-10-26 10:49:42,403:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2021-10-26 10:49:42,404:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:42,593:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:42,593:INFO:Creating metrics dataframe
2021-10-26 10:49:42,718:INFO:Initializing Ada Boost Classifier
2021-10-26 10:49:42,812:INFO:Total runtime is 1.9670886278152466 minutes
2021-10-26 10:49:42,890:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:42,891:INFO:Initializing create_model()
2021-10-26 10:49:42,892:INFO:create_model(estimator=ada, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:42,892:INFO:Checking exceptions
2021-10-26 10:49:42,892:INFO:Importing libraries
2021-10-26 10:49:42,893:INFO:Copying training dataset
2021-10-26 10:49:42,896:INFO:Defining folds
2021-10-26 10:49:42,897:INFO:Declaring metric variables
2021-10-26 10:49:42,957:INFO:Importing untrained model
2021-10-26 10:49:43,021:INFO:Ada Boost Classifier Imported succesfully
2021-10-26 10:49:43,138:INFO:Starting cross validation
2021-10-26 10:49:43,140:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:46,080:INFO:Calculating mean and std
2021-10-26 10:49:46,080:INFO:Creating metrics dataframe
2021-10-26 10:49:46,106:INFO:Uploading results into container
2021-10-26 10:49:46,107:INFO:Uploading model into container now
2021-10-26 10:49:46,108:INFO:create_model_container: 9
2021-10-26 10:49:46,109:INFO:master_model_container: 9
2021-10-26 10:49:46,109:INFO:display_container: 2
2021-10-26 10:49:46,142:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=8185)
2021-10-26 10:49:46,143:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:46,324:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:46,324:INFO:Creating metrics dataframe
2021-10-26 10:49:46,402:INFO:Initializing Gradient Boosting Classifier
2021-10-26 10:49:46,402:INFO:Total runtime is 2.0269246260325113 minutes
2021-10-26 10:49:46,457:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:46,459:INFO:Initializing create_model()
2021-10-26 10:49:46,461:INFO:create_model(estimator=gbc, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:46,461:INFO:Checking exceptions
2021-10-26 10:49:46,462:INFO:Importing libraries
2021-10-26 10:49:46,463:INFO:Copying training dataset
2021-10-26 10:49:46,468:INFO:Defining folds
2021-10-26 10:49:46,469:INFO:Declaring metric variables
2021-10-26 10:49:46,513:INFO:Importing untrained model
2021-10-26 10:49:46,560:INFO:Gradient Boosting Classifier Imported succesfully
2021-10-26 10:49:46,653:INFO:Starting cross validation
2021-10-26 10:49:46,657:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:52,359:INFO:Calculating mean and std
2021-10-26 10:49:52,359:INFO:Creating metrics dataframe
2021-10-26 10:49:52,440:INFO:Uploading results into container
2021-10-26 10:49:52,441:INFO:Uploading model into container now
2021-10-26 10:49:52,442:INFO:create_model_container: 10
2021-10-26 10:49:52,442:INFO:master_model_container: 10
2021-10-26 10:49:52,443:INFO:display_container: 2
2021-10-26 10:49:52,463:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 10:49:52,463:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:52,642:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:52,642:INFO:Creating metrics dataframe
2021-10-26 10:49:52,768:INFO:Initializing Linear Discriminant Analysis
2021-10-26 10:49:52,768:INFO:Total runtime is 2.1330185850461323 minutes
2021-10-26 10:49:52,816:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:52,817:INFO:Initializing create_model()
2021-10-26 10:49:52,818:INFO:create_model(estimator=lda, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:52,819:INFO:Checking exceptions
2021-10-26 10:49:52,820:INFO:Importing libraries
2021-10-26 10:49:52,821:INFO:Copying training dataset
2021-10-26 10:49:52,827:INFO:Defining folds
2021-10-26 10:49:52,828:INFO:Declaring metric variables
2021-10-26 10:49:52,888:INFO:Importing untrained model
2021-10-26 10:49:52,935:INFO:Linear Discriminant Analysis Imported succesfully
2021-10-26 10:49:53,045:INFO:Starting cross validation
2021-10-26 10:49:53,049:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:49:53,800:INFO:Calculating mean and std
2021-10-26 10:49:53,800:INFO:Creating metrics dataframe
2021-10-26 10:49:53,820:INFO:Uploading results into container
2021-10-26 10:49:53,820:INFO:Uploading model into container now
2021-10-26 10:49:53,820:INFO:create_model_container: 11
2021-10-26 10:49:53,820:INFO:master_model_container: 11
2021-10-26 10:49:53,820:INFO:display_container: 2
2021-10-26 10:49:53,820:INFO:LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
                           solver='svd', store_covariance=False, tol=0.0001)
2021-10-26 10:49:53,820:INFO:create_model() succesfully completed......................................
2021-10-26 10:49:54,009:INFO:SubProcess create_model() end ==================================
2021-10-26 10:49:54,009:INFO:Creating metrics dataframe
2021-10-26 10:49:54,104:INFO:Initializing Extra Trees Classifier
2021-10-26 10:49:54,104:INFO:Total runtime is 2.155291732152303 minutes
2021-10-26 10:49:54,157:INFO:SubProcess create_model() called ==================================
2021-10-26 10:49:54,159:INFO:Initializing create_model()
2021-10-26 10:49:54,159:INFO:create_model(estimator=et, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:49:54,160:INFO:Checking exceptions
2021-10-26 10:49:54,160:INFO:Importing libraries
2021-10-26 10:49:54,161:INFO:Copying training dataset
2021-10-26 10:49:54,164:INFO:Defining folds
2021-10-26 10:49:54,165:INFO:Declaring metric variables
2021-10-26 10:49:54,207:INFO:Importing untrained model
2021-10-26 10:49:54,252:INFO:Extra Trees Classifier Imported succesfully
2021-10-26 10:49:54,344:INFO:Starting cross validation
2021-10-26 10:49:54,347:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:50:05,714:INFO:Calculating mean and std
2021-10-26 10:50:05,839:INFO:Creating metrics dataframe
2021-10-26 10:50:05,892:INFO:Uploading results into container
2021-10-26 10:50:05,894:INFO:Uploading model into container now
2021-10-26 10:50:05,895:INFO:create_model_container: 12
2021-10-26 10:50:05,895:INFO:master_model_container: 12
2021-10-26 10:50:05,895:INFO:display_container: 2
2021-10-26 10:50:05,897:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=8185, verbose=0,
                     warm_start=False)
2021-10-26 10:50:05,929:INFO:create_model() succesfully completed......................................
2021-10-26 10:50:06,105:INFO:SubProcess create_model() end ==================================
2021-10-26 10:50:06,105:INFO:Creating metrics dataframe
2021-10-26 10:50:06,606:INFO:Initializing Light Gradient Boosting Machine
2021-10-26 10:50:06,606:INFO:Total runtime is 2.363663053512573 minutes
2021-10-26 10:50:06,648:INFO:SubProcess create_model() called ==================================
2021-10-26 10:50:06,649:INFO:Initializing create_model()
2021-10-26 10:50:06,650:INFO:create_model(estimator=lightgbm, fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023CF7D70520>, kwargs={})
2021-10-26 10:50:06,650:INFO:Checking exceptions
2021-10-26 10:50:06,651:INFO:Importing libraries
2021-10-26 10:50:06,651:INFO:Copying training dataset
2021-10-26 10:50:06,654:INFO:Defining folds
2021-10-26 10:50:06,655:INFO:Declaring metric variables
2021-10-26 10:50:06,688:INFO:Importing untrained model
2021-10-26 10:50:06,722:INFO:Light Gradient Boosting Machine Imported succesfully
2021-10-26 10:50:06,793:INFO:Starting cross validation
2021-10-26 10:50:06,796:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:50:41,139:INFO:Calculating mean and std
2021-10-26 10:50:41,139:INFO:Creating metrics dataframe
2021-10-26 10:50:41,170:INFO:Uploading results into container
2021-10-26 10:50:41,171:INFO:Uploading model into container now
2021-10-26 10:50:41,172:INFO:create_model_container: 13
2021-10-26 10:50:41,172:INFO:master_model_container: 13
2021-10-26 10:50:41,173:INFO:display_container: 2
2021-10-26 10:50:41,176:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=8185, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2021-10-26 10:50:41,177:INFO:create_model() succesfully completed......................................
2021-10-26 10:50:41,354:INFO:SubProcess create_model() end ==================================
2021-10-26 10:50:41,354:INFO:Creating metrics dataframe
2021-10-26 10:50:41,581:INFO:Initializing create_model()
2021-10-26 10:50:41,582:INFO:create_model(estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, verbose=False, system=False, metrics=None, add_to_model_list=True, display=None, kwargs={})
2021-10-26 10:50:41,585:INFO:Checking exceptions
2021-10-26 10:50:41,586:INFO:Importing libraries
2021-10-26 10:50:41,587:INFO:Copying training dataset
2021-10-26 10:50:41,588:INFO:Defining folds
2021-10-26 10:50:41,589:INFO:Declaring metric variables
2021-10-26 10:50:41,590:INFO:Importing untrained model
2021-10-26 10:50:41,590:INFO:Declaring custom model
2021-10-26 10:50:41,594:INFO:Gradient Boosting Classifier Imported succesfully
2021-10-26 10:50:41,597:INFO:Cross validation set to False
2021-10-26 10:50:41,597:INFO:Fitting Model
2021-10-26 10:50:45,309:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 10:50:45,309:INFO:create_models() succesfully completed......................................
2021-10-26 10:50:45,777:INFO:create_model_container: 13
2021-10-26 10:50:45,777:INFO:master_model_container: 13
2021-10-26 10:50:45,778:INFO:display_container: 2
2021-10-26 10:50:45,780:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 10:50:45,781:INFO:compare_models() succesfully completed......................................
2021-10-26 10:51:00,483:INFO:Initializing create_model()
2021-10-26 10:51:00,483:INFO:create_model(estimator=gbc, fold=5, round=4, cross_validation=True, predict=True, fit_kwargs=None, groups=None, refit=True, verbose=True, system=True, metrics=None, add_to_model_list=True, display=None, kwargs={})
2021-10-26 10:51:00,483:INFO:Checking exceptions
2021-10-26 10:51:00,483:INFO:Preparing display monitor
2021-10-26 10:51:00,593:INFO:Importing libraries
2021-10-26 10:51:00,593:INFO:Copying training dataset
2021-10-26 10:51:00,593:INFO:Defining folds
2021-10-26 10:51:00,593:INFO:Declaring metric variables
2021-10-26 10:51:00,624:INFO:Importing untrained model
2021-10-26 10:51:00,734:INFO:Gradient Boosting Classifier Imported succesfully
2021-10-26 10:51:00,797:INFO:Starting cross validation
2021-10-26 10:51:00,813:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:51:06,580:INFO:Calculating mean and std
2021-10-26 10:51:06,580:INFO:Creating metrics dataframe
2021-10-26 10:51:06,641:INFO:Finalizing model
2021-10-26 10:51:09,699:INFO:Uploading results into container
2021-10-26 10:51:09,699:INFO:Uploading model into container now
2021-10-26 10:51:09,823:INFO:create_model_container: 14
2021-10-26 10:51:09,824:INFO:master_model_container: 14
2021-10-26 10:51:09,825:INFO:display_container: 3
2021-10-26 10:51:09,875:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 10:51:09,876:INFO:create_model() succesfully completed......................................
2021-10-26 10:51:18,748:INFO:Initializing tune_model()
2021-10-26 10:51:18,749:INFO:tune_model(estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=5, round=4, n_iter=10, custom_grid={'learning_rate': [0.1, 0.2, 0.5], 'n_estimators': [100, 500, 1000], 'min_samples_split': [1, 2, 5, 10], 'max_depth': [1, 3, 9]}, optimize=AUC, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=False, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, display=None, kwargs={})
2021-10-26 10:51:18,751:INFO:Checking exceptions
2021-10-26 10:51:18,763:INFO:Preparing display monitor
2021-10-26 10:51:19,000:INFO:Copying training dataset
2021-10-26 10:51:19,005:INFO:Checking base model
2021-10-26 10:51:19,006:INFO:Base model : Gradient Boosting Classifier
2021-10-26 10:51:19,051:INFO:Declaring metric variables
2021-10-26 10:51:19,090:INFO:Defining Hyperparameters
2021-10-26 10:51:19,376:INFO:custom_grid: {'actual_estimator__learning_rate': [0.1, 0.2, 0.5], 'actual_estimator__n_estimators': [100, 500, 1000], 'actual_estimator__min_samples_split': [1, 2, 5, 10], 'actual_estimator__max_depth': [1, 3, 9]}
2021-10-26 10:51:19,376:INFO:Tuning with n_jobs=-1
2021-10-26 10:51:19,376:INFO:Initializing RandomizedSearchCV
2021-10-26 10:54:59,269:INFO:best_params: {'actual_estimator__n_estimators': 500, 'actual_estimator__min_samples_split': 2, 'actual_estimator__max_depth': 3, 'actual_estimator__learning_rate': 0.1}
2021-10-26 10:54:59,269:INFO:Hyperparameter search completed
2021-10-26 10:54:59,269:INFO:SubProcess create_model() called ==================================
2021-10-26 10:54:59,284:INFO:Initializing create_model()
2021-10-26 10:54:59,284:INFO:create_model(estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=True, verbose=True, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023C88231F70>, kwargs={'n_estimators': 500, 'min_samples_split': 2, 'max_depth': 3, 'learning_rate': 0.1})
2021-10-26 10:54:59,284:INFO:Checking exceptions
2021-10-26 10:54:59,284:INFO:Importing libraries
2021-10-26 10:54:59,284:INFO:Copying training dataset
2021-10-26 10:54:59,284:INFO:Defining folds
2021-10-26 10:54:59,291:INFO:Declaring metric variables
2021-10-26 10:54:59,334:INFO:Importing untrained model
2021-10-26 10:54:59,334:INFO:Declaring custom model
2021-10-26 10:54:59,391:INFO:Gradient Boosting Classifier Imported succesfully
2021-10-26 10:54:59,483:INFO:Starting cross validation
2021-10-26 10:54:59,487:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 10:55:28,432:INFO:Calculating mean and std
2021-10-26 10:55:28,432:INFO:Creating metrics dataframe
2021-10-26 10:55:28,501:INFO:Finalizing model
2021-10-26 10:55:42,937:INFO:Uploading results into container
2021-10-26 10:55:42,937:INFO:Uploading model into container now
2021-10-26 10:55:42,937:INFO:create_model_container: 15
2021-10-26 10:55:42,937:INFO:master_model_container: 15
2021-10-26 10:55:42,937:INFO:display_container: 4
2021-10-26 10:55:42,937:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 10:55:42,937:INFO:create_model() succesfully completed......................................
2021-10-26 10:55:43,126:INFO:SubProcess create_model() end ==================================
2021-10-26 10:55:43,194:INFO:create_model_container: 15
2021-10-26 10:55:43,194:INFO:master_model_container: 15
2021-10-26 10:55:43,195:INFO:display_container: 4
2021-10-26 10:55:43,197:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 10:55:43,198:INFO:tune_model() succesfully completed......................................
2021-10-26 10:56:00,396:INFO:Initializing tune_model()
2021-10-26 10:56:00,397:INFO:tune_model(estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=5, round=4, n_iter=10, custom_grid={'learning_rate': [0.1, 0.2, 0.5], 'n_estimators': [100, 500, 1000], 'min_samples_split': [1, 2, 5, 10], 'max_depth': [1, 3, 9]}, optimize=AUC, custom_scorer=None, search_library=scikit-learn, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=False, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, display=None, kwargs={})
2021-10-26 10:56:00,397:INFO:Checking exceptions
2021-10-26 10:56:00,402:INFO:Preparing display monitor
2021-10-26 10:56:00,482:INFO:Copying training dataset
2021-10-26 10:56:00,487:INFO:Checking base model
2021-10-26 10:56:00,488:INFO:Base model : Gradient Boosting Classifier
2021-10-26 10:56:00,529:INFO:Declaring metric variables
2021-10-26 10:56:00,575:INFO:Defining Hyperparameters
2021-10-26 10:56:00,799:INFO:custom_grid: {'actual_estimator__learning_rate': [0.1, 0.2, 0.5], 'actual_estimator__n_estimators': [100, 500, 1000], 'actual_estimator__min_samples_split': [1, 2, 5, 10], 'actual_estimator__max_depth': [1, 3, 9]}
2021-10-26 10:56:00,799:INFO:Tuning with n_jobs=-1
2021-10-26 10:56:00,799:INFO:Initializing RandomizedSearchCV
2021-10-26 10:59:35,594:INFO:best_params: {'actual_estimator__n_estimators': 500, 'actual_estimator__min_samples_split': 2, 'actual_estimator__max_depth': 3, 'actual_estimator__learning_rate': 0.1}
2021-10-26 10:59:35,594:INFO:Hyperparameter search completed
2021-10-26 10:59:35,594:INFO:SubProcess create_model() called ==================================
2021-10-26 10:59:35,594:INFO:Initializing create_model()
2021-10-26 10:59:35,594:INFO:create_model(estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=StratifiedKFold(n_splits=5, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=True, verbose=True, system=False, metrics=None, add_to_model_list=True, display=<pycaret.internal.Display.Display object at 0x0000023C882ECB50>, kwargs={'n_estimators': 500, 'min_samples_split': 2, 'max_depth': 3, 'learning_rate': 0.1})
2021-10-26 10:59:35,594:INFO:Checking exceptions
2021-10-26 10:59:35,594:INFO:Importing libraries
2021-10-26 10:59:35,594:INFO:Copying training dataset
2021-10-26 10:59:35,608:INFO:Defining folds
2021-10-26 10:59:35,609:INFO:Declaring metric variables
2021-10-26 10:59:35,654:INFO:Importing untrained model
2021-10-26 10:59:35,656:INFO:Declaring custom model
2021-10-26 10:59:35,703:INFO:Gradient Boosting Classifier Imported succesfully
2021-10-26 10:59:35,809:INFO:Starting cross validation
2021-10-26 10:59:35,812:INFO:Cross validating with StratifiedKFold(n_splits=5, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 11:00:05,655:INFO:Calculating mean and std
2021-10-26 11:00:05,655:INFO:Creating metrics dataframe
2021-10-26 11:00:05,752:INFO:Finalizing model
2021-10-26 11:00:20,641:INFO:Uploading results into container
2021-10-26 11:00:20,641:INFO:Uploading model into container now
2021-10-26 11:00:20,641:INFO:create_model_container: 16
2021-10-26 11:00:20,641:INFO:master_model_container: 16
2021-10-26 11:00:20,641:INFO:display_container: 5
2021-10-26 11:00:20,641:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 11:00:20,656:INFO:create_model() succesfully completed......................................
2021-10-26 11:00:20,845:INFO:SubProcess create_model() end ==================================
2021-10-26 11:00:20,912:INFO:create_model_container: 16
2021-10-26 11:00:20,914:INFO:master_model_container: 16
2021-10-26 11:00:20,915:INFO:display_container: 5
2021-10-26 11:00:20,917:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 11:00:20,917:INFO:tune_model() succesfully completed......................................
2021-10-26 11:00:25,075:INFO:Initializing finalize_model()
2021-10-26 11:00:25,076:INFO:finalize_model(estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fit_kwargs=None, groups=None, model_only=True, display=None)
2021-10-26 11:00:25,078:INFO:Finalizing GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 11:00:25,081:INFO:Initializing create_model()
2021-10-26 11:00:25,082:INFO:create_model(estimator=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), fold=None, round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=True, verbose=False, system=False, metrics=None, add_to_model_list=False, display=None, kwargs={})
2021-10-26 11:00:25,082:INFO:Checking exceptions
2021-10-26 11:00:25,083:INFO:Importing libraries
2021-10-26 11:00:25,083:INFO:Copying training dataset
2021-10-26 11:00:25,085:INFO:Defining folds
2021-10-26 11:00:25,085:INFO:Declaring metric variables
2021-10-26 11:00:25,085:INFO:Importing untrained model
2021-10-26 11:00:25,086:INFO:Declaring custom model
2021-10-26 11:00:25,089:INFO:Gradient Boosting Classifier Imported succesfully
2021-10-26 11:00:25,089:INFO:Starting cross validation
2021-10-26 11:00:25,092:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2021-10-26 11:01:32,505:INFO:Calculating mean and std
2021-10-26 11:01:32,505:INFO:Creating metrics dataframe
2021-10-26 11:01:32,521:INFO:Finalizing model
2021-10-26 11:01:52,359:INFO:create_model_container: 16
2021-10-26 11:01:52,359:INFO:master_model_container: 16
2021-10-26 11:01:52,359:INFO:display_container: 6
2021-10-26 11:01:52,359:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 11:01:52,359:INFO:create_model() succesfully completed......................................
2021-10-26 11:01:52,572:INFO:create_model_container: 16
2021-10-26 11:01:52,572:INFO:master_model_container: 16
2021-10-26 11:01:52,573:INFO:display_container: 5
2021-10-26 11:01:52,575:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2021-10-26 11:01:52,575:INFO:finalize_model() succesfully completed......................................
2021-10-26 11:01:53,381:INFO:Initializing save_model()
2021-10-26 11:01:53,381:INFO:save_model(model=GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8185, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), model_name=model, prep_pipe_=Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=['yearsAtCompany',
                                                          'averageMonthlyHours'],
                                      target='turnover', time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None...
                ('P_transform', 'passthrough'), ('binn', 'passthrough'),
                ('rem_outliers', 'passthrough'), ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='turnover')),
                ('fix_perfect', Remove_100(target='turnover')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False), verbose=True, kwargs={})
2021-10-26 11:01:53,381:INFO:Adding model into prep_pipe
2021-10-26 11:01:53,584:INFO:model.pkl saved in current working directory
2021-10-26 11:01:53,616:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=['yearsAtCompany',
                                                          'averageMonthlyHours'],
                                      target='turnover', time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None...
                                            learning_rate=0.1, loss='deviance',
                                            max_depth=3, max_features=None,
                                            max_leaf_nodes=None,
                                            min_impurity_decrease=0.0,
                                            min_impurity_split=None,
                                            min_samples_leaf=1,
                                            min_samples_split=2,
                                            min_weight_fraction_leaf=0.0,
                                            n_estimators=500,
                                            n_iter_no_change=None,
                                            presort='deprecated',
                                            random_state=8185, subsample=1.0,
                                            tol=0.0001, validation_fraction=0.1,
                                            verbose=0, warm_start=False)]],
         verbose=False)
2021-10-26 11:01:53,616:INFO:save_model() successfully completed......................................
